title: Sruthik's Blog
email: psruthik@gmail.com
description: >- 
  Stuff about Computer Graphics
baseurl: "" 
url: "https://k3wlbuddy.github.io" 
github_username:  K3WLBUDDY


markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
