title: K3WLBUDDY's Blog
email: psruthik@gmail.com
description: >- 
  Random thoughts of a Person into stuff
baseurl: "" 
url: "https://k3wlbuddy.github.io" 
github_username:  K3WLBUDDY


markdown: kramdown
theme: minima
plugins:
  - jekyll-feed